name: Infrastructure
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v1

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: npm ci

      - name: Bootstrap stack
        run: npm run cdk bootstrap

      - name: Deploy stack
        run: npm run cdk-deploy